.github/workflows/auto-pr-update-icon.yml

[SH-11231](https://shoplworks.atlassian.net/browse/SH-11231)
- 아이콘 플러그인 추가에 대한 PR 자동화 작업
[SH-11231]: https://shoplworks.atlassian.net/browse/SH-11231?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[SH-11231] 아이콘 플러그인 추가

---

sdg/src/main/java/com/shopl/sdg/component/indicator/SDGTextIndicator.kt

[SH-11547](https://shoplworks.atlassian.net/browse/SH-11547)
[SH-11547]: https://shoplworks.atlassian.net/browse/SH-11547?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[SH-11547] SDG Component > Indicator > Text Indicator

---

sdg/src/main/java/com/shopl/sdg/template/multi_calendar/SDGMultiCalendar.kt

[SH-11598](https://shoplworks.atlassian.net/browse/SH-11598)
- 기존 SDGMultiCalendarModal 에서 기간 선택만 가능한 문제가 있어, 단일 날짜 선택 케이스 추가
- maxCount == 1인 경우 단일 날짜 선택 모드로 동작
- BottomSheetModal이 아닌, BottomSheetState로 동작하고 있어 Preview를 위하여 메소드 분리
[SH-11598]: https://shoplworks.atlassian.net/browse/SH-11598?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[SH-11598] SDG Template > Multi Calendar 단일 선택 옵션 기능 수정

---

sdg/src/main/java/com/shopl/sdg/template/form/SDGForm.kt

[SH-11605](https://shoplworks.atlassian.net/browse/SH-11605)
- Template > Form > Selected Input에 SDGSelectedInputSingle 아이콘 추가
- 등급 선택 Form에서 주로 사용됨
[SH-11605]: https://shoplworks.atlassian.net/browse/SH-11605?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[SH-11605] SDG Template > Form > Selected Input 아이콘 정보 추가

---

sdg/src/main/java/com/shopl/sdg/template/multi_calendar/SDGMultiCalendar.kt

[SH-11598](https://shoplworks.atlassian.net/browse/SH-11598)
- 일별 캘린더 단일 선택 시 선택된 날짜 표기 수정
[SH-11598]: https://shoplworks.atlassian.net/browse/SH-11598?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[SH-11598] SDG Template > Multi Calendar 단일 선택 옵션 기능 수정 - 일별 날짜 표기 수정

---

sdg/src/main/java/com/shopl/sdg/template/form/SDGSimpleInputForm.kt

[SH-11557](https://shoplworks.atlassian.net/browse/SH-11557)
-  Template > Form > Simple Input 에서 키보드 옵션 받도록 수정
[SH-11557]: https://shoplworks.atlassian.net/browse/SH-11557?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[SH-11557] SDG Template > Form > Simple Input 추가 - 키보드 옵션 추가

---

.github/release-drafter-config.yml
.github/workflows/release-drafter.yml

[SH-11645](https://shoplworks.atlassian.net/browse/SH-11645)
릴리즈 drafter 및 태깅 자동화
[SH-11645]: https://shoplworks.atlassian.net/browse/SH-11645?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[SH-11645] 릴리즈 drafter 및 태깅 자동화

---

.github/workflows/create_pr.yml

[SH-11646](https://shoplworks.atlassian.net/browse/SH-11646)
- PR 정보 자동화
- PR 제목
- Reviewers 지정
- Assignees 지정
- labels 지정
PR 정보 자동화 action을 생성했습니다.
PR 생성 시 컨벤션에 맞춰 내용만 작성해주시고 생성하시면 일정 시간 후 action이 실행되면서 다른 항목들은 자동으로 채워지게 됩니다.
- reviewers는 요금제 문제로 기존처럼 한명만 지정되지만, 업그레이드시 자동으로 android team인원 모두가 reviewers에 추가됩니다.
- PR 제목(지라 이슈 타이틀) 및 labels는 브랜치 명을 파싱하므로 브랜치 명 컨벤션을 반드시 지켜주시기 바랍니다.
[SH-11646]: https://shoplworks.atlassian.net/browse/SH-11646?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[SH-11646] PR 컨벤션 자동화

---

sdg/src/main/java/com/shopl/sdg/component/button/bottom/SDGBottomButton.kt
sdg/src/main/java/com/shopl/sdg/component/button/box/SDGBoxButton.kt
sdg/src/main/java/com/shopl/sdg/component/button/box/SDGBoxButtonSize.kt
sdg/src/main/java/com/shopl/sdg/component/button/box/SDGBoxButtonType.kt
sdg/src/main/java/com/shopl/sdg/component/button/capsule/SDGCapsuleButton.kt
sdg/src/main/java/com/shopl/sdg/component/button/capsule/SDGCapsuleButtonSize.kt
sdg/src/main/java/com/shopl/sdg/component/button/capsule/SDGCapsuleButtonType.kt
sdg/src/main/java/com/shopl/sdg/component/button/ghost/SDGGhostButton.kt
sdg/src/main/java/com/shopl/sdg/component/button/ghost/SDGGhostButtonSize.kt
sdg/src/main/java/com/shopl/sdg/component/checkbox/SDGCheckBox.kt

[SH-11519](https://shoplworks.atlassian.net/browse/SH-11519)
- SDG 내 디자인 작업 완료된 컴포넌트들에 한하여 개발 컨벤션에 맞게 Type,Size 등 분리
[SH-11519]: https://shoplworks.atlassian.net/browse/SH-11519?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[SH-11519] Type, Size 등을 디자인 시스템 요소 구현부와 분리

---

sdg-common/src/main/java/com/shopl/sdg_common/ui/components/IOText.kt

[SH-11722](https://shoplworks.atlassian.net/browse/SH-11722)
- IOText deprecated 처리
[SH-11722]: https://shoplworks.atlassian.net/browse/SH-11722?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[SH-11722] [Android] IOText Deprecated 처리

---

sdg-resource/src/main/res/drawable/ic_common_photo.xml
sdg-resource/src/main/res/drawable/ic_remove_m.xml
sdg/src/main/java/com/shopl/sdg/component/thumbnail/Thumbnails.kt

[SH-11747](https://shoplworks.atlassian.net/browse/SH-11747)
[SH-11747]: https://shoplworks.atlassian.net/browse/SH-11747?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[SH-11747] [Android] SDG Com > Thumbnails 신규

---

build-logic/src/main/kotlin/com/shopl/sdg/build_logic/PublishingConfig.kt

update version to 1.0.3

---

build-logic/src/main/kotlin/com/shopl/sdg/build_logic/PublishingConfig.kt

1.0.6 버전 업데이트

---

build-logic/src/main/kotlin/com/shopl/sdg/build_logic/PublishingConfig.kt

1.0.7 버전 업데이트

---

build-logic/src/main/kotlin/com/shopl/sdg/build_logic/PublishingConfig.kt

1.0.8 버전 업데이트

---

gradle/libs.versions.toml
sdg-common/build.gradle.kts

Coil 라이브러리 사용 시 필요한 네트워킹 라이브러리 추가하였습니다.
https://coil-kt.github.io/coil/README-ko/

Coil 네트워킹 라이브러리 추가

---

sdg-common/src/main/java/com/shopl/sdg_common/foundation/SDGColor.kt

[SH-12052](https://shoplworks.atlassian.net/browse/SH-12052)
[SH-12052]: https://shoplworks.atlassian.net/browse/SH-12052?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[SH-12052] [Android] SDGColor > Special CG 추가

---

build-logic/src/main/kotlin/com/shopl/sdg/build_logic/PublishingConfig.kt

1.0.9 버전 업데이트

---

build-logic/src/main/kotlin/com/shopl/sdg/build_logic/PublishingConfig.kt

1.1.0 버전 업데이트

---

sdg/src/main/java/com/shopl/sdg/component/check_option/SDGCheck.kt
sdg/src/main/java/com/shopl/sdg/template/check_option_label/SDGCheckOptionLabel.kt
sdg/src/main/java/com/shopl/sdg/template/check_option_label/SDGCheckOptionLabelSize.kt

[SH-12247](https://shoplworks.atlassian.net/browse/SH-12247)
- [Check Option Label](https://www.figma.com/design/qWVshatQ9eqoIn4fdEZqWy/SDG?node-id=19392-9158&m=de) 업데이트
`SDGCheck` 파일 내 변경 사항이 있긴하나 `Check Option Label` 변경사항에 대한 수정 내용입니다.
`SDGCheck`도 디자인시스템 내 수정사항이 따로 있기 때문에 주석 추가 및 별도로 코드를 수정하지는 않았습니다.
추후 필요 시 티켓을 생성하여 작업하겠습니다.
[SH-12247]: https://shoplworks.atlassian.net/browse/SH-12247?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[SH-12247] [Android] SDG Template > Check Option List Item -> Check Option Label로 업데이트

---

sdg/src/main/java/com/shopl/sdg/template/popup/SDGBottomPopup.kt
sdg/src/main/java/com/shopl/sdg/template/popup/SDGPopup.kt

[SH-12703](https://shoplworks.atlassian.net/browse/SH-12703)
[SH-12703]: https://shoplworks.atlassian.net/browse/SH-12703?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[SH-12703] [Android] SDG Template > Popup > Bottom Popup - 여백 및 하단 툴 박스 수정

---

build-logic/src/main/kotlin/com/shopl/sdg/build_logic/PublishingConfig.kt

1.1.2 버전 업데이트

---

build-logic/src/main/kotlin/com/shopl/sdg/build_logic/PublishingConfig.kt

1.1.3 버전 업데이트

---

sdg/src/main/java/com/shopl/sdg/template/popup/SDGPopup.kt

[SH-12761](https://shoplworks.atlassian.net/browse/SH-12761)
[SH-12761]: https://shoplworks.atlassian.net/browse/SH-12761?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[SH-12761] [Android] SDG Template > Popup > Bottom Popup - 바텀 버튼 세로 구분선 라인 색상 수정

---

build-logic/src/main/kotlin/com/shopl/sdg/build_logic/PublishingConfig.kt

1.1.5 버전 업데이트

---

sdg/src/main/java/com/shopl/sdg/component/text_input/simple/SDGSimpleTextInput.kt
sdg/src/main/java/com/shopl/sdg/component/util/simple_text_input/SDGSimpleTextInput.kt

[SH-13195](https://shoplworks.atlassian.net/browse/SH-13195)
- 주민등록번호 마스킹 기능 구현을 위해 VisualTransformation 옵션이 필요합니다. 
- 향후 숫자 3자리수 콤마 로직도 VisualTransformation로 대체 가능할 것 같습니다. 
[SH-13195]: https://shoplworks.atlassian.net/browse/SH-13195?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[SH-13195] [Android] SDGSimpleTextInput - VisualTransformation 옵션 추가

---

sdg-common/src/main/java/com/shopl/sdg_common/foundation/spacing/SDGSpacing.kt
sdg/src/main/java/com/shopl/sdg/template/popup/list/anatomy/SDGListPopupBody.kt

[SH-13192](https://shoplworks.atlassian.net/browse/SH-13192)
- [미사용 Spacing 제거](https://shopl-workspace.slack.com/archives/C08GX3Z9JE5/p1756856233472139)
- ListPopupBody 수정
- 미사용 Spacing 제거 대응
- 디자인 시스템과 맞지 않는 padding 수정
- 컨벤션과 맞지 않는 주석 제거 및 접근 제한자 수정
[SH-13192]: https://shoplworks.atlassian.net/browse/SH-13192?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[SH-13192] [Android] 사용하지 않는 Spacing 제거

---

sdg-common/src/main/java/com/shopl/sdg_common/foundation/SDGColor.kt

[SH-13227](https://shoplworks.atlassian.net/browse/SH-13227)
[SH-13227]: https://shoplworks.atlassian.net/browse/SH-13227?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[SH-13227] [Android] SDGColor > Special RP 추가

---

sdg-common/src/main/java/com/shopl/sdg_common/foundation/SDGColor.kt

[SH-13271](https://shoplworks.atlassian.net/browse/SH-13271)
- SDGColor > SpecialYG 추가
[SH-13271]: https://shoplworks.atlassian.net/browse/SH-13271?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[SH-13271] [Android] SDGColor > Special YG 추가

---

sdg/src/main/java/com/shopl/sdg/component/icon_label/SDGIconLabel.kt
sdg/src/main/java/com/shopl/sdg/component/icon_label/SDGIconLabelPreviewProvider.kt

[SH-13276](https://shoplworks.atlassian.net/browse/SH-13276)
- 사용성 개선을 위한 Ripple 효과 제거
- preview provider 추가
[SH-13276]: https://shoplworks.atlassian.net/browse/SH-13276?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[SH-13276] [Android] Icon Label Ripple 효과 제거

---

sdg/src/main/java/com/shopl/sdg/template/form/SDGForm.kt

[SH-13454](https://shoplworks.atlassian.net/browse/SH-13454)
[SH-12454]: https://shoplworks.atlassian.net/browse/SH-12454?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[SH-13454]: https://shoplworks.atlassian.net/browse/SH-13454?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[SH-13454] Template > Form > Select Form > Typography 변경

---

build-logic/src/main/kotlin/com/shopl/sdg/build_logic/PublishingConfig.kt

버전 업데이트 1.1.8

---

build-logic/src/main/kotlin/com/shopl/sdg/build_logic/PublishingConfig.kt

버전 업데이트 1.1.9

---

sdg/src/main/java/com/shopl/sdg/component/tab/SDGLineFixedTab.kt

[SH-13478](https://shoplworks.atlassian.net/browse/SH-13478)
[SH-13478]: https://shoplworks.atlassian.net/browse/SH-13478?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[SH-13478] [Android] Line Fixed Tab 디자인 가이드 최신화

---

sdg/src/main/java/com/shopl/sdg/component/empty_icon/SDGBasicEmpty.kt

[SH-13548](https://shoplworks.atlassian.net/browse/SH-13548)
[SH-13548]: https://shoplworks.atlassian.net/browse/SH-13548?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[SH-13548] [Android] 가이드 최신화
